#!/bin/bash

rm -rf build/*
mkdir -p build

# All files
echo "Compile TypeScript"
node_modules/.bin/tsc \
  --declaration \
  --module commonjs \
  --noImplicitAny \
  --noEmitOnError \
  --removeComments \
  --noFallthroughCasesInSwitch \
  --noImplicitReturns \
  --outDir build \
  typings/tsd.d.ts src/*

echo "Bundle type definitions"
node dts-bundle.js
